FirebaseAuth/FirebaseAuth.gd, FirebaseAuth/FirebaseUserData.gd
Hey. thanks for your work.
I added handling `login_failed` case for auth. :smile: 
and added a function for getting user data.
=> Handle login_failed case

Demo/ChatControl.gd, Demo/Control.tscn, Demo/FirebaseLoginAndDB.tscn, Demo/Login.gd, Demo/addons/GDFirebase/Firebase.gd, Demo/addons/GDFirebase/FirebaseAuth.gd, Demo/addons/GDFirebase/FirebaseDatabase.gd, Demo/addons/GDFirebase/FirebaseFirestore.gd, Demo/addons/GDFirebase/FirebaseReference.gd, Demo/addons/GDFirebase/FirebaseStorage.gd, Demo/addons/GDFirebase/Store.gd, Demo/project.godot
Due to not having a Firebase Storage REST API, I'm leaving this in but will have to come back to it. For now, it contains a lot of refactoring that fixes some serious bugs.
=> Beginning Storage, incomplete implementation

Demo/addons/GDFirebase/FirebaseAuth.gd, GDFirebase/FirebaseAuth.gd
#36 
Fixing capitalization of refresh token
- refreshToken -> refreshtoken
- expiresIn -> expiresin
=> Fixing Refresh Token

addons/godot-firebase/FirebaseAuth.gd
This change focuses on adding some new Firebase Auth features that were missing. New features added include
* Sending a password reset email
* Deleting a User Account (As in user deletes their own account)
* Change email or password (Logged in user can change these)
* Send account verification email
This closes #58
=> New Firebase auth features

addons/godot-firebase/auth/auth.gd, addons/godot-firebase/firestore/firestore_collection.gd, addons/godot-firebase/firestore/firestore_document.gd, project.godot
This PR will integrate automatic parsing/marshalling of `FirestoreDocument`s in `FirestoreCollection` functions.
Previously, to call `FirestoreCollection` management functions such as `add(document_name, document)` and `update(document_name, document)` it was necessary to create a `FirestoreDocument` and call a parsing function `dict2fields(dictionary)` in order to parse a GDscript `Dictionary` to a formatted body accepted by Firestore API (which is in the form of `{fields: { var_type: {name:value} }}`).
In the same way, Firebase return bodies needed to be formatted to a Dictionary in order to make them more readable and usable in gdscript using the function `fields2dict(document.fields)`.
| Firebase | GDScript |
|-----------|-----------|
|``` {fields: {string: {"user":"user_name"}}} …
```
=> added FirestoreCollection internal parsing

addons/godot-firebase/database/database.gd, addons/godot-firebase/database/reference.gd
=> changed name of private variables

addons/godot-firebase/auth/auth.gd, addons/godot-firebase/containers/container.gd, addons/godot-firebase/database/database.gd, addons/godot-firebase/database/reference.gd, addons/godot-firebase/database/resource.gd, addons/godot-firebase/firebase/firebase.gd, addons/godot-firebase/firestore/firestore.gd, addons/godot-firebase/firestore/firestore_collection.gd, addons/godot-firebase/firestore/firestore_document.gd, addons/http-sse-client/HTTPSSEClient.gd
related to #85 #80 
- added parsing for Firebase `mapValue`, now it is possible to directly pass nested dictionaries without arrays handling them
```gdscript
collection.add(DOCUMENT_ID, { "a_string":"STRING", "an_array":["array"], "a_dictionary": {"key":"value"} }
```
Everything is also properly parsed back to string in Godot to print it directly
=> add mapValue parsing + fix indentation document.gd

addons/godot-firebase/firestore/firestore_collection.gd
`get()` was connecting to `add_document` signal and vice versa.
=> Switch get and add document connections

addons/godot-firebase/auth/auth.gd
=> Fix password change function

addons/godot-firebase/auth/auth.gd, addons/godot-firebase/database/reference.gd, addons/godot-firebase/dynamiclinks/dynamiclinks.gd, addons/godot-firebase/firestore/firestore.gd, addons/godot-firebase/storage/storage_reference.gd
Remove offline support temporarily to fix bug, fix json header and remove access-control-allow-origin
=> Big fixes for HTML export prep

addons/silicon.util.custom_docs/plugin.gd
There is a large memory leak and some bugs associated with the documentation plugin at the moment, so we need to disable it for the time being.
=> Remove docs plugin temporarily

addons/godot-firebase/auth/auth.gd
#191 
#189 
this PR adds a first implementation of `custom token` support feature to log in using a custom token.
Currently a custom token needs to be generated outside of our  addon.
added:
`Firebase.Auth.login_with_custom_token(token : String)`
If the request is successful, the `login_succeeded(auth : Dictionary)` will be emitted in the same way as all the other signals, and the client will be automatically authenticated.
This feature needs to be tested
=> add custom_token support

addons/godot-firebase/firestore/firestore_task.gd
=> Fix Task.TASK_LIST

addons/godot-firebase/firestore/firestore_task.gd
=> Request query list

addons/godot-firebase/auth/auth.gd
This PR changes the error handling of the auth files. 
- Adds a new signal for 'signup_failed'
`signal signup_failed(code, message)`
- Adds new ENUM for Auth_Type
`enum Auth_Type {
NONE = -1
LOGIN_EP,
LOGIN_ANON,
LOGIN_CT,
LOGIN_OAUTH,
SIGNUP_EP
}`
- Adds new var for auth_request_type that uses ENUM
`var auth_request_type : int = -1`
All login and signup functions have a new line to delcare the 'auth_request_type'. This is then used in the error to send the correct type of signal to the user.
>         if requesting == Requests.EXCHANGE_TOKEN:
>             emit_signal("token_exchanged", false)
>             emit_signal("login_failed", res.error, res.error_description)
>             emit_signal("auth_request", res.error, res.error_description)
>         else:
>             var sig = …
=> Signal added, error handle changed, enum added

addons/godot-firebase/firebase/firebase.gd
This adds the line missing in firebase.gd to all the URI prefix to the config. Wihthout it no one will be able to use dynamic links
=> add uri prefix to config

addons/godot-firebase/auth/auth.gd
=> Fix manual_token_refresh

addons/godot-firebase/database/database_store.gd, addons/godot-firebase/database/reference.gd
This will close #241 
This PR still needs a bit of testing to make sure it works before merging into the main branch.
=> Rtdb delete

addons/godot-firebase/auth/auth.gd
- when running the emulator locally the refresh token url needs to point to the local server also
- Content-Type needs to be application/json
- local api documentation says `identitytoolkit.googleapis.com` is required between the version
These are just things I saw while trying to test auth emulation, I figured I'd make a PR for review, but I don't know if the emulators are currently working for others or not.
=> Fix auth emulation

addons/godot-firebase/auth/auth.gd, addons/godot-firebase/firebase/firebase.gd
* Added static types for Firebase classes in `firebase.gd`
* Made `load_auth`, `save_auth` and `check_auth` return boolean values
* Added a default value for some configuration properties
=> Smaller fixes

addons/godot-firebase/firestore/firestore_task.gd
Backwards compatible changes related to #358
=> Prevent hanging thread

addons/godot-firebase/auth/auth.gd
OAuth2 with Facebook give error auth.accestoken because of wrong response reading.
=> Fixed error with OAuth 2 fb login flow

addons/godot-firebase/auth/auth.gd
Added a function to link an anonymous account with an oAuth2 account via a token provided by the account being linked to
=> #382 added link_with_credential function

addons/godot-firebase/auth/auth.gd
- Added function call to remove auth file after user account is successfully deleted
- Replaced tabs used for indentation with spaces
=> Remove auth file after successful account deletion

addons/godot-firebase/storage/storage.gd
Updated storage.gd to properly report errors.
=> Fix storage error handling 3.x

addons/godot-firebase/storage/storage.gd
Updated storage.gd to properly report errors.
=> Fix storage error handling

addons/godot-firebase/auth/auth.gd
Closes #436 
This PR solves the issue with login succeeded signal emitted twice when using oauth.
=> fix_oAuth_login_succeeded_emitting_twice

addons/godot-firebase/Utilities.gd, addons/godot-firebase/firestore/firestore_collection.gd, addons/godot-firebase/firestore/firestore_document.gd
Loading a Vector2/Vector2i from a string wasn't working as intended, this pull request fixes that.
=> fixed being able to load a string into a Vector2/Vector2i

addons/http-sse-client/HTTPSSEClient.gd
This has indeed been tested in the test harness and all seems well.
=> Fix HTTPSSEClient to correctly parse all events sent in one message (fixes #443)

addons/godot-firebase/auth/auth.gd
=> Remove JavaScript tag check

addons/godot-firebase/example.env, addons/godot-firebase/firebase/firebase.gd, addons/godot-firebase/firestore/firestore.gd
Adding new value "databaseName" to config and replacing the database name in the _extended_url variable. Also defaulting it to "(default)" to preserve it's previous behaviour.
=> Fixing https://github.com/GodotNuts/GodotFirebase/issues/474
