GodotNuts/GodotFirebase

FirebaseAuth/FirebaseAuth.gd
the keys are renamed in `func get_clean_keys`.
after that, `auth` does not have `refreshToken` or `refresh_token` but only has `refreshtoken`
and `auth = get_clean_keys(auth)` is already called in here, right just before calling `begin_fresh_countdown()`.
https://github.com/WolfgangSenff/GodotFirebase/blob/b380007b693809cd19b19b7c3a912b625aad5125/FirebaseAuth/FirebaseAuth.gd#L50-L54
so no need to call it again.
=> Fix refresh_token is null

Demo/Control.tscn, Demo/MainTheme.tres, Demo/addons/GDFirebase/Store.gd, Demo/default_env.tres, GDFirebase/Store.gd
Sometimes, when the Store got a null piece of data (which can happen for some unknown reason), it would occasionally rewrite the root dictionary with it. This fixes that by never allowing the root dictionary to be rewritten with null data.
=> Fix Store.gd null data rewrite issue

GDFirebase/FirebaseFirestoreCollection.gd
This is to fix issue #39 with the fix from @Zarasan.
I looked for any line that contained:
var url = _get_request_url() + separator + documentId
and replaced it with
var url = _get_request_url() + separator + documentId.replace(" ", "%20")
This fix closes #39
=> add .replace(" ", "%20") to fix documentID Issue

addons/godot-firebase/Firebase.gd, override.cfg
Latest PRs cut out the `ovverride.cfg` that was left in the old `plugin` subfolder of the repository.
This PR will add the file back in order to let people configure Firebase inside the Project Settings window within the Editor.
The `override.cfg` is a configuration file that Godot Engine automatically reads to extend the Project Settings.
Any line in the .cfg, if properly set up, will be added in Project Settings sidelist after the file is added to the root of the project and the project has been reloaded (just a quit and open will work).
*Changes:*  
- fff8101 just adds the file back;
- 215e649 changes the override.cfg structure, adding a `firebase/` root in the settings' category. This will make the setting inside Project Settings even more readable. See below as an example:
*old …
=> Add override.cfg back for in-editor Plugin configuration.

addons/godot-firebase/database/reference.gd, addons/godot-firebase/database/resource.gd, project.godot
This PR will change how `FirebaseResource` is structured as well as these changes will refelct in `FirebaseDatabaseReference`.
`FirebaseResource` now has a `key` value which is internally modified, removing the first `/` and returning just the document name.
This will let users have directly returned the document name without having the first trail simbol.
Since the path character is removed from the key, to the `update` function in `FirebaseDatabaseReference` will internally add it inside the request path, so that to update a document, the arguments will just be `update(resource.key, new_data)`
=> changed key value in database reference

addons/godot-firebase/firestore/firestore_document.gd
- Add new array2fields function that formats Arrays for Firestore
correctly.
- Change dict2fields function to use array2fields on Arrays.
- Both array2fields and dict2fields recursively call one another to
parse the entire object.
- Return new object from dict2fields instead of modifying object passed
in, so that calling it twice on the same object doesn't break it. 
This works with the following test object I was trying to save to firestore:
```
var islandData = {
'ground': [
{
'x': 0,
'y': 0
},
{
'x': 1,
'y': 0
}
],
'towers': [
{
'x': 0,
'y': 0,
'upgrades': []
},
{
'x': 1,
'y': 0,
'upgrades': [
{
'id': 'flamethrower',
'level': 2,
'attachpos': 'main'
}
]
}
]
}
```
=> Add parsing of nested Dictionaries/Arrays

addons/godot-firebase/auth/auth.gd, addons/godot-firebase/database/database.gd, addons/godot-firebase/database/reference.gd, addons/godot-firebase/firebase/firebase.gd, addons/godot-firebase/firebase/firebase.tscn, addons/godot-firebase/firestore/firestore.gd, addons/godot-firebase/storage/storage.gd, addons/godot-firebase/storage/storage_reference.gd, addons/godot-firebase/storage/storage_task.gd, addons/http-sse-client/HTTPSSEClient.gd, project.godot, test/TestUtils.gd, test/unit/test_FirebaseDatabaseStore.gd
This pull request will bring a firebase cloud storage API to this wonderful project.
It adds the following features.
- Uploading data to storage
- Downloading data from storage
- List directories and files in storage
- Delete file in storage
- retrieving and updating file metadata
- Works with authentication
=> Cloud Storage API

addons/godot-firebase/auth/auth.gd
This will close #95 
The code now checks to make sure opening the file does not result in an error state. as long as var err == 0 or OK then everything will work. If not it will print out the error code to the console and continue along.
I checked this in my own project by saving a file with a password I set, and then opening it with a different one. Instead of crashing, the console printed "Error opening file. Error code: 16"
=> Fix for hard crashes when trying to open file

addons/godot-firebase/auth/auth.gd
This was causing issues when exporting the application to HTML5. It was erroring out saying `"Content-Type " is not a valid header`. I guess because it does a split on the `:`
=> Remove space after Content-Type header

addons/godot-firebase/dynamiclinks/dynamiclinks.gd
In https://github.com/GodotNuts/GodotFirebase/commit/b617ce35a21c4e31946156607722e42819ccdad6 in #120 `DynamicLinks._set_config()` is called, but this function doesn't have an underscore before it, causing this plugin to crash upon launch. 
Added the underscore so it doesn't crash.
=> Add underscore before set_config in dynamic links

addons/godot-firebase/storage/storage.gd
Fixes #135
I changed ref.full_path to just ref. Because _get_file_url() requires StorageReference.
=> Fix _get_file_url call

addons/godot-firebase/firestore/firestore_document.gd, test/unit/test_FirebaseDatabaseStore.gd, test/unit/test_FirestoreDocument.gd
- Fix deserialization of an array with dictionaries inside of it. Fixes #131 
- Add test for FirestoreDocument to prevent regressions.
- Convert tabs to spaces in existing test file to be consistent with core plugin using spaces.
=> Fix Firestore Deserialization of Arrays

addons/godot-firebase/firestore/firestore.gd, addons/godot-firebase/firestore/firestore_task.gd
This will close #161 
There is an issue when you try to use .get() in firestore on a document that does not exist. If you also have collection connected for errors, you will crash the plugin. This is because the error function from firestore_collection is looking for three arguments, but the error function in firestore_task only passes one.
I changed the line to
`emit_signal("error", data.code, 0, data.message)`
This will satisfy the number of arguments as well as the accepted type. Need to discuss if hard coding a 0 is worth it or if we should use something else.
=> Fix issue #161 - Firestore .get() issue

addons/godot-firebase/firestore/firestore.gd, addons/godot-firebase/firestore/firestore_collection.gd, addons/godot-firebase/firestore/firestore_task.gd
This PR will change the following
- Break out the errors in Firestore tasks to a per task error
- Change the firestore.gd file to accept the different signals from the task errors
- Remove `null` from the delete document function since it was throwing a random error
- Remove the requirements for a type of data in the error code in firestore_collection
The idea is that breaking out the signals and functions will allow us to have better control over the data that is sent and not try to force it into a single function. This PR has been built so that the end user should not have to update their code at all, but the behind the scenes functions work better.
This PR will close the following:
close #166
=> Firestore cleanup signals

addons/godot-firebase/auth/auth.gd
New function reduces need to look at auth internals, as well as supports better handling for when requests fail or otherwise wouldn't raise signals before. With this change, a developer can always depend on the signal being emitted, so they can handle the callback state as needed.
This will indeed emit this signal on more code branches than before, which should be properly tested for any unexpected behavior for anyone who depends on connecting a response function to  and was already somehow separately handling these branch cases
=> Added auth.is_logged_in() function and ensure `auth_request` always signaled

addons/godot-firebase/database/reference.gd
This script emits the signal but the signal was never created.
https://github.com/GodotNuts/GodotFirebase/blob/8a4a962c87c3f8850a85b97b9f3744975c2cc881/addons/godot-firebase/database/reference.gd#L89
=> fix: add delete_data_update signal

addons/godot-firebase/auth/auth.gd
Accidentally used the wrong path for the refresh token, sorry about that
=> Fix auth emulator refresh token endpoint

addons/godot-firebase/auth/auth.gd, addons/godot-firebase/database/database.gd, addons/godot-firebase/database/reference.gd, addons/godot-firebase/dynamiclinks/dynamiclinks.gd, addons/godot-firebase/firebase/firebase.gd, addons/godot-firebase/firestore/firestore.gd, addons/godot-firebase/functions/functions.gd, addons/godot-firebase/storage/storage.gd, addons/http-sse-client/HTTPSSEClient.gd
I've added comments for all my code changes to better explain them.
- Make auth_request signal values match expected results
- fix database emulation + workaround for events
- some small cleanup things
Related issues:
(https://github.com/firebase/firebase-tools/issues/3329)
#154
=> Fixing Database emulation

addons/godot-firebase/firestore/firestore_document.gd
A recursive algorithm has been added in order to support direct referencing of subkeys i complex paths
For example
```
"FIRST_LEVEL"
├─ "SECOND_LEVEL_1" : "VALUE_1"
└─ "SECOND_LEVEL_2" : "VALUE_2"
```
`SECOND_LEVEL_1` value can now be updated without overwriting the whole document, in this way:
```gdscript
Firebase.Firestore.collection("...").update("<document>", { "FIRST_LEVEL.SECOND_LEVEL_1":"VALUE_1" }})
```
=> Dot notation

addons/godot-firebase/firestore/firestore.gd, addons/godot-firebase/firestore/firestore_task.gd
I have switched around the errors so that we have just one error, and it includes the task that was attempting to happen when the error occurred. This can give our users a lot more info about what was happening and maybe give them a better way to handle their errors when one occurs. This also removes all the extra error signals we had, as they made it prohibitive to hook up to when you might be doing multiple, complex things in your use of the plugin.
=> Refactor firestore_task for better error handling

addons/godot-firebase/functions/functions.gd
As requested on the issues page, here is a simple PR to fix the missing GET parameters for Functions
=> Fix: Parameters not being passed to Firebase using GET method

addons/godot-firebase/Utilies.gd, addons/godot-firebase/auth/auth.gd, addons/godot-firebase/database/database.gd, addons/godot-firebase/dynamiclinks/dynamiclinks.gd, addons/godot-firebase/firestore/firestore.gd, addons/godot-firebase/functions/functions.gd
* disable gzip compression on web export, as this results in HTTPRequest returning an empty body due to a failure in decompression
* also check for "Web" in OS.get_name() ("HTML5" appears to be an old value)
=> Fixes an issue with HTTPRequest on web exports

addons/godot-firebase/firestore/firestore_task.gd
I found a potential issue for a hanging await. He is my example code which should help explain things:
```
func check_if_doc_exists(player_name) -> int:
var document_task = scores_collection.get_doc(player_name)
var document = await document_task.get_document
if document != null:
return document.doc_fields.score
return 0
```
In the code above, if the `get_doc` emits a `task_error` signal the `await document_task.get_document` will never return and I think it just hangs there. 
One way to solve this currently is to use `await document_task.task_finished` instead but that seems a bit confusing to newcomers to the library like myself. To me, it makes sense to await the expected signal and check if the returned value is correct or not. Returning a null or empty array on error seems like a …
=> Prevent hanging await and return relative value

addons/godot-firebase/auth/auth.gd
The redirect_uri param always defaulted to http://localhost:8060 even when using a port other than default on function call get_auth_localhost.
**The relevant issue number, if applicable.**
No issue has been opened.
**Any new features that have been added**
Added a setter to _local_port to re-create the _local_uri var according to the port specified.
**Any relevant tests that have been run**
No relevant test have been run or written
=> Redirect to correct local port after OAuth2 success

addons/godot-firebase/firestore/firestore_collection.gd
Fixed by adding a bool parameter to the _on_delete_document function in firestore_collection.gd
=> Fix for #372 delete_document error

addons/godot-firebase/auth/auth.gd
Replaced `OS.has_feature('JavaScript')` with` OS.has_feature('web')`, as the JavaScript feature tag is removed for Godot 4.
Solves the issue #379 
According to Godot documentation : [Feature tags](https://docs.godotengine.org/en/4.2/tutorials/export/feature_tags.html) and [Example](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html#calling-javascript-from-script)
=> Fix #379: Replaced "JavaScript" feature tag.

addons/godot-firebase/storage/storage.gd
I was trying to create a new file in the Firebase Storage with space characters in the file name, e.g:
```gdscript
Firebase.Storage.ref("path with space/image.png").put_file("res://image.png")
```
But it would fail, even if Firebase allows paths to have spaces. Turns out it was because the space character wasn't being encoded in the url parameter, only the forward slash `/` was.
Using the ~`uri_encode()`~ `http_escape`, it should encode both the slash and space characters, as well as any other character.
~The target is set to `main`, but can switch to `4.x` if that's the correct branch.~
EDIT: my base branch was created from `main`, so updated to use the godot 3 function instead
=> Storage paths can now have space characters

addons/godot-firebase/storage/storage.gd
Same as #387, but for the `4.0` branch.
I was trying to create a new file in the Firebase Storage with space characters in the file name, e.g:
```gdscript
Firebase.Storage.ref("path with space/image.png").put_file("res://image.png")
```
But it would fail, even if Firebase allows paths to have spaces. Turns out it was because the space character wasn't being encoded in the url parameter, only the forward slash `/` was.
Using the `uri_encode()`, it should encode both the slash and space characters, as well as any other character.
=> [Godot 4] Storage paths can now have space characters

addons/godot-firebase/firestore/firestore_task.gd
Attempts to address #364 by mapping values from the `FirestoreTask.Task` enum to printable descriptions of those actions.
=> #364 Provide user-friendly error codes for Firestore tasks

addons/godot-firebase/Utilities.gd
While experimenting with retrieving data from Firebase, I encountered an issue where a value wasn't being converted to an Array.  This PR adds a fields2array conversion for arrayValue types, assuming there isn't a reason it was excluded—happy to be educated if so!
Tested by making the change to the local copy of this plugin in my project and can confirm that it converts the { "arrayValue" : { ... } } to an array as expected.
=> Add arrayValue conversion to from_firebase_type

addons/godot-firebase/firestore/firestore_document.gd
fix: check that request result has fields property
=> Fix Request with empty list of fields crash bug

addons/godot-firebase/auth/auth.gd
Add a function to link an account with email/password. Useful for converting an anonymous user account into an email account.
=> Add link_account() function

addons/godot-firebase/Utilities.gd
Functionality added to support #447
=> added support for converting stringValues to and from Vector2 & Vector2i
